<a href="https://colab.research.google.com/github/esraaelhady/esraaelhady.github.io/blob/master/numpy_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install numpy

In [6]:
import numpy as np
arr1 = np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


In [7]:
arr2 = [10,20,30,40,50,60]
print(arr2[0:2])

[10, 20]


In [15]:
arr3=[[10,20,30],[40,50,60]]
print(arr3)
print(arr3[0][0])

[[10, 20, 30], [40, 50, 60]]
10


In [20]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.full((3,3),7))
print(np.eye((3)))
print(np.random.random((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.57543319 0.58020863 0.26664503]
 [0.93619976 0.73016598 0.60003106]
 [0.18770261 0.40855488 0.57408141]]


In [22]:
f1=[[10,20,30],[40,50,60],[70,80,90]]
f2=[[1,2,3],[4,5,6],[7,8,9]]
print(np.multiply(f1,f2))

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
